# flask-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: flask-app
  namespace: gym-app
spec:
  selector:
    app: flask-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30080
  type: NodePort

