# mysql-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: gym-app
spec:
  selector:
    app: mysql
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  clusterIP: None  # headless service for stateful connection

