# Admin: full access
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: admin-role
  namespace: gym-app
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]

---
# Developer: Deploy-only
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: developer-role
  namespace: gym-app
rules:
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["create", "update", "patch", "get", "list", "watch"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]

---
# Observer: Read-only
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: observer-role
  namespace: gym-app
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["get", "list", "watch"]

